apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
data:
  ME_CONFIG_MONGODB_ADMINUSERNAME: root
  ME_CONFIG_MONGODB_ADMINPASSWORD: example # так не хорошо, на практике будет передавать через secrets
  ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

