---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicaset
spec:
# Говорим сколько реплик нашего приложения мы хотим запустить (по факту сколько подов)
  replicas: 4
# На основании лейбла в селекторе мы понимаем какие поды относятся к нашему ReplicaSet
  selector:
    matchLabels:
      app: my-app
# мы описываем шаблон пода и выше говорим кубу с помощью ReplicaSet создай из этого шаблона 2 пода 
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - image: nginx:1.12
        name: nginx
        ports:
        - containerPort: 80

